src/Services/Masa.Auth.Service.Admin/Application/Subjects/TeamCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Program.cs, src/Services/Masa.Auth.Service.Admin/Services/OssService.cs
sync local json file and k8s secret get
=> feat:dapr secret

src/Contracts/Masa.Auth.Contracts.Admin/Infrastructure/Constants/CacheKey.cs, src/Contracts/Masa.Auth.Contracts.Admin/Infrastructure/Constants/MasaStackConsts.cs, src/Contracts/Masa.Auth.Contracts.Admin/Subjects/UserSystemDataDto.cs, src/Contracts/Masa.Auth.Contracts.Admin/Subjects/Validator/UserSystemDataDtoValidator.cs, src/Services/Masa.Auth.Service.Admin/Application/Permissions/PermissionCacheCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Permissions/QueryHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Permissions/RoleCacheCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/SaveUserSystemBusinessDataCommand.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/SaveUserSystemBusinessDataCommandValidator.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/LdapCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/QueryHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/UserCacheCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Domain/Subjects/Aggregates/UserSystemBusinessData.cs, src/Services/Masa.Auth.Service.Admin/Domain/Subjects/EventHandlers/UserDomainEventHandler.cs, src/Services/Masa.Auth.Service.Admin/Domain/Subjects/Services/UserDomainService.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/AuthDbContext.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/AuthDbContextSeed.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/EntityConfigurations/Subjects/UserSystemBusinessDataEntityTypeConfiguration.cs, src/Services/Masa.Auth.Service.Admin/Migrations/20220718073639_AddUserSystemBusinessData.Designer.cs, src/Services/Masa.Auth.Service.Admin/Migrations/20220718073639_AddUserSystemBusinessData.cs, src/Services/Masa.Auth.Service.Admin/Services/UserService.cs, src/Services/Masa.Auth.Service.Admin/appsettings.Development.json
add usersytembizdata and fix teampermission issues
=> feat(user):user system data

src/Services/Masa.Auth.Service.Admin/Application/Subjects/OperationLogCommandHandler.cs
=> Fix(build code):fix build error

src/Services/Masa.Auth.Service.Admin/Infrastructure/Extensions/Extensions.cs, src/Services/Masa.Auth.Service.Admin/Program.cs
=> chore: Adjust the writing method

src/Contracts/Masa.Auth.Contracts.Admin/Subjects/Validator/SyncStaffValidator.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs
=> Fix(login、staff sync): fix issues

src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/Position/Position.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Roles/Role.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/ApiResource/ApiResource.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/ApiScope/ApiScope.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/Client/Client.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/CustomLoginRegister.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/IdentityResource/IdentityResource.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/UserClaim/UserClaim.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/Team.razor
=> Fix(all page):fix all page scroll

src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/Permissions/PermissionExtensionConfigure.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/Team.razor
=> Fix(team、permission):fix team page、permission config

src/Services/Masa.Auth.Service.Admin/Services/UserService.cs
=> Feature:register user add return userModel

src/Services/Masa.Auth.Service.Admin/Infrastructure/Sms/Sms.cs
=> Feature(send sms expiration): update send sms expiration

.gitignore, Directory.Build.props, src/Contracts/Masa.Auth.Contracts.Admin/Infrastructure/Utils/ListExtensions.cs, src/Contracts/Masa.Auth.Contracts.Admin/Subjects/Validator/AddUserValidator.cs, src/Contracts/Masa.Auth.Contracts.Admin/Subjects/Validator/UpdateUserValidator.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/QueryHandler.cs, src/Services/Masa.Auth.Service.Admin/Program.cs, src/Web/Masa.Auth.Security.OAuth.Providers/Infrastructure/ThirdPartyIdpCaller/ThirdPartyIdpCallerBase.cs, src/Web/Masa.Auth.Security.OAuth.Providers/Infrastructure/ThirdPartyIdpCaller/ThirdPartyIdpCallerProvider.cs, src/Web/Masa.Auth.Security.OAuth.Providers/Infrastructure/ThirdPartyIdpCaller/WeChatCaller.cs, src/Web/Masa.Auth.Security.OAuth.Providers/Masa.Auth.Security.OAuth.Providers.csproj, src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/Permissions/PermissionExtensionConfigure.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/Permissions/PermissionsConfigure.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/Permissions/PermissionsConfigure.razor.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/Position/Position.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/Position/Position.razor.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/TeamAdmin.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/TeamMember.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/SyncStaffDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/ThirdPartyUser.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Shared/AdminCompontentBase.cs, src/Web/Masa.Auth.Web.Sso/Infrastructure/Validations/ThirdPartyIdpGrantValidator.cs
=> Fix issues 1.0

Directory.Build.props, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Queries/UserSystemBusinessDataQuery.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/QueryHandler.cs, src/Services/Masa.Auth.Service.Admin/Program.cs, src/Services/Masa.Auth.Service.Admin/Services/UserService.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj
=> Feature(userService) :user service GetSystemListDataAsync supprot multiple userIds

Directory.Build.props, src/Services/Masa.Auth.Service.Admin/Application/Messages/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/AddUserCommandValidator.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Queries/LdapDetailQuery.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/QueryHandler.cs, src/Services/Masa.Auth.Service.Admin/Services/ThirdPartyIdpService.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj, src/Web/Masa.Auth.Web.Sso/Infrastructure/Validations/LdapGrantValidator.cs, src/Web/Masa.Auth.Web.Sso/Masa.Auth.Web.Sso.csproj, src/Web/Masa.Auth.Web.Sso/Program.cs, src/Web/Masa.Auth.Web.Sso/_Imports.cs
=> Feature(sso): add sso login by ldap

src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj
=> Feature:update nuget packge

src/Contracts/Masa.Auth.Contracts.Admin/Infrastructure/Utils/MasaAbstractValidator.cs, src/Contracts/Masa.Auth.Contracts.Admin/Subjects/Validator/AddUserValidator.cs, src/Contracts/Masa.Auth.Contracts.Admin/_import.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Shared/AdminCompontentBase.cs
=> Feature(MasaAbstractValidator):add MasaAbstractValidator、fix issues

src/Services/Masa.Auth.Service.Admin/Application/Messages/Commands/SendEmailCommandValidator.cs, src/Services/Masa.Auth.Service.Admin/Application/Messages/Commands/SendSmsCommandValidator.cs
=> Fix(SendSmsCode):fix send sms code not validate

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Logs/OperationLog.razor
after modification effect draw:
=> fix: operation log interface with UI design draw be difference

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/ConfigLogin.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/ConfigRegister.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/LoginRegisterTemplate.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/UpdateCustomLoginRegisterDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/css/masa-auth.css
=> fix:custom confiuration login interface with UI design draw be difference

src/Contracts/Masa.Auth.Contracts.Admin/Subjects/Validator/SyncStaffValidator.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/UpdateUserCommandValidator.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/UpsertUserCommandValidator.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/SyncStaffDialog.razor
=> Fix issues 0309

src/Services/Masa.Auth.Service.Admin/Domain/Subjects/EventHandlers/UserDomainEventHandler.cs
=> Feature(Autocomplete):Set autoComplete add log

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/AddSheet.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/Team.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/TeamBasicInfo.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/TeamCard.razor, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/css/masa-auth.css, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/i18n/zh-CN.json
=> fix: Team module style issues

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/LoginRegisterTemplate.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/UpdateCustomLoginRegisterDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/css/masa-auth.css
=> fix:page part content is hidden at 1080P resolution

src/Services/Masa.Auth.Service.Admin/Services/UserService.cs
=> Fix(userService) user service GetSystemDataAsync error

src/Services/Masa.Auth.Service.Admin/Services/UserService.cs
=> Fix(userService):fix userService  GetSystemListDataAsync error

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/Staff.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/Staff.razor.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/ThirdPartyUser.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/ThirdPartyUser.razor.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/User.razor, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/css/masa-auth.css
=> feat:update user list css

src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs
Modify the UserSplicingDataAsync method. When the employee is frozen, the staff id is Guid. Empty
=> Modify employee freeze not to display team

src/Web/Masa.Auth.Web.Sso/Pages/Account/Login/Model/LoginInputModelValidator.cs, src/Web/Masa.Auth.Web.Sso/Pages/Account/Login/Model/RegisterInputModelValidator.cs, src/Web/Masa.Auth.Web.Sso/Pages/Account/Login/RegisterSections/PhoneNumber.razor, src/Web/Masa.Auth.Web.Sso/wwwroot/i18n/zh-CN.json
=> fix promt message at account login page

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/css/masa-auth.css
=> fix:Permission user, missing user and team avatar

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/ButtonGroup.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor
Permission list. The plus sign of the new permission is fixed
=> feat:Permission list. The plus sign of the new permission is fixed

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/AddApiPermission.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/AddMenuPermission.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/css/masa-auth.css
=> style: set permission code input font-size to 16px,same as prefix

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/Client/Section/Authentication.razor
=> fix:Edit client, authentication page, URL misalignment. resolved #800

src/Services/Masa.Auth.Service.Admin/Application/Subjects/TeamCommandHandler.cs
=> fix:Fix role binding times error

src/Services/Masa.Auth.Service.Admin/Application/Permissions/QueryHandler.cs
=> fix:If the user has no child permissions, the parent menu is displayed. resolved #797

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor.cs
=> feat:The optimization menu cannot be at the same level as the element

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/PlaceholderTextField.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/CopyOrgSheet.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/OrgSheet.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/AddStaffDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/AddUserDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/UpdateStaffDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/UpdateUserDialog.razor
style: adjust the nickname placeholder style according to ui design
resolve #830
=> style: adjust the nickname placeholder style according to ui design

src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs
Fix the issue [Employee upload, prompt information error](https://github.com/masastack/MASA.Auth/issues/758)
=> Fix: Employee upload, prompt information error -- issue 758 

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor
=> fix:Menu permissions cannot change the location

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor.cs
=> fix:Confirm the permission URL field requirements. resolved #796

src/Services/Masa.Auth.Service.Admin/Application/Sso/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Assets/I18n/en-US.json, src/Services/Masa.Auth.Service.Admin/Assets/I18n/zh-CN.json, src/Services/Masa.Auth.Service.Admin/Infrastructure/Constants/UserFriendlyExceptionCodes.cs, src/Services/Masa.Auth.Service.Admin/_Imports.cs
=> fix:The client id must be unique. resolved #828

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor
=> fix:Permission list. The last level does not expand the collapse button. resolved #823

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/SyncStaffDialog.razor.cs
Fixed this [Issue-843](https://github.com/masastack/MASA.Auth/issues/843)
=> Fix: Clear upload file, when close SyncStaffDialog - Issue 843

src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj, src/Web/Masa.Auth.Web.Admin.Rcl/Shared/AdminCompontentBase.cs
chore: update blazor to 1.0.0 preview 9
=> chore: update blazor to 1.0.0 preview 9

src/Web/Masa.Auth.Web.Sso/Pages/Account/Login/LoginSection.razor, src/Web/Masa.Auth.Web.Sso/wwwroot/css/masa-blazor-pro.css
Fix login tab style and select drop down style
=> fix: login style

src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs
=> Fix(user):fix upsert user character code is overwritten

src/Contracts/Masa.Auth.Contracts.Admin/Infrastructure/Constants/CacheKey.cs, src/Services/Masa.Auth.Service.Admin/Application/Permissions/PermissionCacheCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Permissions/QueryHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/AddTeamCommand.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/SyncTeamRedisCommand.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/QueryHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/TeamCacheCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/TeamCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/UserCacheCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Domain/Subjects/EventHandlers/UserDomainEventHandler.cs, src/Services/Masa.Auth.Service.Admin/Domain/Subjects/Repositories/ITeamRepository.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/CacheModels/CachePermission.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/CacheModels/CacheStaffTeam.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/Repositories/TeamRepository.cs
测试视频，更新用户角色之后，会更新缓存并且查询全部走缓存。如视频所见
[20230321201020.webm](https://user-images.githubusercontent.com/38368335/226603037-f032f944-afb1-4870-bcc0-979c668ed198.webm)
=> fix:Permisson Query from Cache. resolved #840

src/Services/Masa.Auth.Service.Admin/Application/Subjects/QueryHandler.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/DefaultCard.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/Staff.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/ThirdPartyUser.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/User.razor
There is [Issue-393](https://github.com/masastack/MASA.Stack.Components/issues/393), Fix recent visited url erro,it will be jump 403.
There is [Issue-848](https://github.com/masastack/MASA.Auth/issues/848), Amend scroll margin
=> Fix: recent visited url error

src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/Team.razor
_Add default(no data) page for all item Card list
Upgrade MASA.Stack.Components package_
* [√] Code compiles correctly
=> Add default(no data) page for all item Card list

src/Web/Masa.Auth.Web.Sso/Pages/Account/Login/LoginSection.razor
Fix [the Issue-863](https://github.com/masastack/MASA.Auth/issues/863)
=> Fix:  environment switchover is invalid

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/Subjects/ExternalThirdPartySelect.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/Subjects/ExternalThirdPartySelect.razor.cs
Fix [Issue-890](https://github.com/masastack/MASA.Auth/issues/890)
=> Fix: upload avatar failed when add thirdpartyidp

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/ThirdPartyUser.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/ThirdPartyUser.razor.cs
Fix [Issue-659](https://github.com/masastack/MASA.Auth/issues/659)
=> Fix: Remove Creator in ThirdPartyIDP

src/Services/Masa.Auth.Service.Admin/Application/Subjects/QueryHandler.cs, src/Web/Masa.Auth.Web.Sso/Infrastructure/AuthenticationExternalHandler.cs
_Account password login is the same as wechat scanning QR code login_
* [√] Code compiles correctly
=> Account password login is the same as wechat scanning QR code login

src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/css/masa-auth.css
Revert table-border-head style
=> Fix: SDataTable style

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/Staff.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/Staff.razor.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/User.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/User.razor.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/UserAuthorizeDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/UserAuthorizeDialog.razor.cs
Fix [Issue-936](https://github.com/masastack/MASA.Auth/issues/936)
=> fix: userauthorizedialog cache

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Logs/OperationLog.razor
=> fix:Operation log, after selecting time, should add clear button

src/Services/Masa.Auth.Service.Admin/Application/Subjects/LdapCommandHandler.cs
Fix [Issue-959](https://github.com/masastack/MASA.Auth/issues/959)
=> fix: add connect test when idap commit

src/Web/Masa.Auth.Web.Sso/Pages/Home/Index.razor, src/Web/Masa.Auth.Web.Sso/_Imports.cs, src/Web/Masa.Auth.Web.Sso/wwwroot/i18n/en-US.json, src/Web/Masa.Auth.Web.Sso/wwwroot/i18n/zh-CN.json
=> refactor:sso home/index page. resolved #978

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/LdapDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/ThirdPartyUser.razor, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/i18n/en-US.json, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/i18n/zh-CN.json
=> fix：Third party user, domain account button and pop-up text adjustment. resolved #960

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Component/Permissions/PermissionExtensionConfigure.cs
Fix [Issue-954](https://github.com/masastack/MASA.Auth/issues/954)
=> fix: top menu permission display error

src/ApiGateways/Masa.Auth.ApiGateways.Caller/Services/Permissions/PermissionService.cs, src/Contracts/Masa.Auth.Contracts.Admin/Infrastructure/Dtos/BaseUpsertDto.cs, src/Services/Masa.Auth.Service.Admin/Domain/Permissions/Aggregates/Permission.cs, src/Services/Masa.Auth.Service.Admin/Program.cs, src/Services/Masa.Auth.Service.Admin/Services/PermissionService.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor.cs, src/Web/Masa.Auth.Web.Admin.Server/Program.cs
feat: after delete/add perminssion should select parent
fix: adjust set permission parent
resolved #949  #970
=> feat: after delete/add perminssion should select parent

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/Position/Position.razor
=> fix:Position, new button style needs to be adjusted

src/ApiGateways/Masa.Auth.ApiGateways.Caller/Masa.Auth.ApiGateways.Caller.csproj, src/ApiGateways/Masa.Auth.ApiGateways.Caller/Services/Permissions/PermissionService.cs, src/Contracts/Masa.Auth.Contracts.Admin/Infrastructure/Dtos/BaseUpsertDto.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor.cs
Roll back some code because IsUpdate got an unexpected value.
=> fix: fix-isUpdate-error-value

src/Web/Masa.Auth.Web.Sso/Pages/Account/Login/RegisterSection.razor, src/Web/Masa.Auth.Web.Sso/Pages/Account/Login/RegisterSection.razor.cs, src/Web/Masa.Auth.Web.Sso/Pages/ProtocolModal.razor
=> fix:Toggle the login/Register tab to trigger the user Agreement window

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Shared/AdminCompontentBase.cs
after add permission  select the added one
=> feat: after add permission  select the added one

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/AddSheet.razor
加载缓慢，是因为加载权限树比较慢。我这边优化成：当还没到该步骤时不加载内容
=> fix:The new team button is slow to load #909

src/Contracts/Masa.Auth.Contracts.Admin/Sso/AddClientBasicDto.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/Client/AddClientDialog.razor.cs
=> SSO: Restore Add client default image

src/Services/Masa.Auth.Service.Admin/Infrastructure/AuthSeedData.cs
Fix [Issue-541](https://github.com/masastack/MASA.Stack.Components/issues/541)  [Issue-539](https://github.com/masastack/MASA.Stack.Components/issues/539)   [Issue-538](https://github.com/masastack/MASA.Stack.Components/issues/538)
=> fix: resolve for seeddata

src/Services/Masa.Auth.Service.Admin/Infrastructure/AuthSeedData.cs
Fix [Issue-551](https://github.com/masastack/MASA.Stack.Components/issues/551)
=> fix: adjust Team order for menu in DCC app.

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/OrgSheet.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/OrgSheet.razor.cs
=> Fix:Organization structure root node cannot be deleted

src/Contracts/Masa.Auth.Contracts.Admin/Permissions/AppPermissionDto.cs, src/Services/Masa.Auth.Service.Admin/Application/Permissions/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Permissions/QueryHandler.cs, src/Services/Masa.Auth.Service.Admin/Domain/Permissions/Aggregates/Permission.cs, src/Services/Masa.Auth.Service.Admin/Domain/Permissions/Repositories/IPermissionRepository.cs, src/Services/Masa.Auth.Service.Admin/Domain/Permissions/Services/PermissionDomainService.cs, src/Services/Masa.Auth.Service.Admin/Domain/Subjects/EventHandlers/UserDomainEventHandler.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/AuthSeedData.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/AddMenuPermission.razor.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Permissions/Index.razor.cs
chore: code spelling and format change
=> chore: code spelling and format change

Directory.Build.props, src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/Organization.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/Position/Position.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/RolePermissions/Roles/Role.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/ApiResource/ApiResource.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/ApiScope/ApiScope.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/Client/Client.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/Client/Section/AddBasics.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/Client/Section/Authentication.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/Client/Section/Basics.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/AddCustomLoginRegisterDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/CustomLoginRegister.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/CustomLoginRegister/UpdateCustomLoginRegisterDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/IdentityResource/IdentityResource.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Sso/UserClaim/UserClaim.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/Team.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/ThirdPartyIdps/ThirdPartyIdp.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/AddUserDialog.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/Staff.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/ThirdPartyUser.razor, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/ThirdPartyUser.razor.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Users/User.razor, src/Web/Masa.Auth.Web.Admin.Rcl/wwwroot/i18n/zh-CN.json
=> Fix issues 492

src/Services/Masa.Auth.Service.Admin/Domain/Subjects/Aggregates/User.cs, src/Web/Masa.Auth.Web.Admin.Rcl/Masa.Auth.Web.Admin.Rcl.csproj
Change comment 
Update Masa.Stack.Component package for DateTimeRangeQuickPicker
=> fix: chage user comment and update Masa.Stack.Component package

src/Services/Masa.Auth.Service.Admin/Assets/I18n/en-US.json, src/Services/Masa.Auth.Service.Admin/Assets/I18n/zh-CN.json
fix: add prompt for PasswordFormat
=> fix: add prompt for PasswordFormat

src/Services/Masa.Auth.Service.Admin/Infrastructure/Sms/Sms.cs
=> Fix(login):fix phoneNumber login ，sms code can be reused

src/Services/Masa.Auth.Service.Admin/Application/Sso/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Assets/I18n/en-US.json, src/Services/Masa.Auth.Service.Admin/Assets/I18n/zh-CN.json, src/Services/Masa.Auth.Service.Admin/Infrastructure/Constants/UserFriendlyExceptionCodes.cs
Fix [Issue-1060](https://github.com/masastack/MASA.Auth/issues/1060)
=> fix: ApiScope and IdentityResource name confict

src/Services/Masa.Auth.Service.Admin/Infrastructure/AuthSeedData.cs
due to https://github.com/masastack/MASA.TSC/pull/425
the path spell is fixed
=> chore: update tsc menu url

src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/Organization.razor
=> fix:icon+ text buttons, ICONS don't need tooltips

src/Services/Masa.Auth.Service.Admin/Infrastructure/AuthSeedData.cs
https://github.com/masastack/MASA.TSC/pull/435
=> fix: tsc url fix

Directory.Build.props, src/Services/Masa.Auth.Service.Admin/Masa.Auth.Service.Admin.csproj, src/Web/Masa.Auth.Security.OAuth.Providers/Apple/AppleBuilder.cs, src/Web/Masa.Auth.Security.OAuth.Providers/Infrastructure/ThirdPartyIdpCaller/AppleCaller.cs, src/Web/Masa.Auth.Security.OAuth.Providers/Infrastructure/ThirdPartyIdpCaller/ThirdPartyIdpCallerProvider.cs, src/Web/Masa.Auth.Security.OAuth.Providers/Masa.Auth.Security.OAuth.Providers.csproj, src/Web/Masa.Auth.Security.OAuth.Providers/_Imports.cs, src/Web/Masa.Auth.Web.Sso/Infrastructure/Validations/ThirdPartyIdpGrantValidator.cs
=> Feature(login):support apple login

src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/Constants/UserFriendlyExceptionCodes.cs, src/Web/Masa.Auth.Web.Sso/wwwroot/i18n/en-US.json, src/Web/Masa.Auth.Web.Sso/wwwroot/i18n/zh-CN.json
_fix: An account can bind multiple wechat signals_
* [√] Code compiles correctly
=> fix: An account can bind multiple wechat signals

src/Web/Masa.Auth.Web.Sso/Infrastructure/Validations/ThirdPartyIdpGrantValidator.cs
=> Fix(login): fix third party login error

src/ApiGateways/Masa.Auth.ApiGateways.Caller/Services/Subjects/ThirdPartyUserService.cs, src/Contracts/Masa.Auth.Contracts.Admin/Subjects/RemoveThirdPartyUserByThridPartyIdentityDto.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/RemoveThirdPartyUserByRemoveThirdPartyUserByThridPartyIdentityCommand.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/ThirdPartyCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Services/ThirdPartyUserService.cs
1.Add  ThirdPartyUserService RemoveByThridPartyIdentity api
=> feat:add RemoveByThridPartyIdentity api

src/Web/Masa.Auth.Web.Sso/Pages/Account/Login/RegisterSection.razor
Fixes masastack/Masa.Stack.Components#615
=> 🐛 fix(sso): i18n doesn't work at login and register sections

.gitlab-ci.yml
=> ci：update ci

.gitlab-ci.yml
=> ci: update ci

src/Services/Masa.Auth.Service.Admin/Application/Permissions/Queries/AppPermissionCodeListQuery.cs, src/Services/Masa.Auth.Service.Admin/Application/Permissions/QueryHandler.cs, src/Services/Masa.Auth.Service.Admin/Services/PermissionService.cs
1、Add GetAppPermissionsAsync
2、Query permissions not used in comments
=> 🆕 feat: Add GetAppPermissionsAsync

src/Services/Masa.Auth.Service.Admin/Application/Sso/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/MapsterAdapterConfig.cs, src/Services/Masa.Auth.Service.Admin/Program.cs
Add asynchronous logic to fetch client details in `CommandHandler.cs` and handle cases where they do not exist. Comment out the adaptation logic for `ClientDetailDto` to avoid potential errors.  
In `MapsterAdapterConfig.cs`, comment out the `IgnoreIf` logic in the mapping configuration from `ClientDetailDto` to `Client` to preserve the mapping of `AllowedScopes`.  
In `Program.cs`, modify the `AddMasaStackConfigAsync` method to add configuration control in debug mode and comment out the hardcoded `identityServerUrl` value in debug mode.  
Add CORS service configuration to allow requests from specific origins and enable CORS support in the middleware pipeline.
=> fix client-side processing and configuration management

.gitlab-ci.yml
=> feat:update gitlab ci file

Directory.Build.props, src/Services/Masa.Auth.Service.Admin/Infrastructure/Extensions/ElasticsearchAutoCompleteExtensions.cs, src/Web/Masa.Auth.Web.Sso/Program.cs
update package versions and improve code quality
=> feat:update package versions and improve code quality

src/Services/Masa.Auth.Service.Admin/Application/Projects/QueryHandler.cs
Removed unnecessary null checks for query.ClientId and directly called RemoveInvisibleMenu. Optimized visibility checks in appNavVisibles to enhance code readability and efficiency.
=> refactor(QueryHandler): simplify menu permission logic

Directory.Build.props, src/Contracts/Masa.Auth.Contracts.Admin/Infrastructure/Constants/UserFriendlyExceptionCodes.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/SyncFromLdapCommand.cs, src/Services/Masa.Auth.Service.Admin/Application/Subjects/StaffCommandHandler.cs, src/Services/Masa.Auth.Service.Admin/Domain/Subjects/Services/LdapDomainService.cs, src/Services/Masa.Auth.Service.Admin/Infrastructure/Extensions/SchedulerJobServiceCollectionExtensions.cs, src/Services/Masa.Auth.Service.Admin/Services/UserService.cs
- Updated `MasaFrameworkPackageVersion` to `1.2.0-preview.10`.
- Added `LDAP_ACCOUNT_ABNORMAL` constant in `UserFriendlyExceptionCodes.cs`.
- Implemented LDAP account status checks in `CommandHandler.cs`.
- Added copyright and namespace in `SyncFromLdapCommand.cs`.
- Enhanced `StaffCommandHandler.cs` with LDAP support fields and `SyncStaffAsync` method for user synchronization.
- Updated user binding logic in `LdapDomainService.cs` to enable/disable users based on LDAP account status.
- Introduced `AddSyncLdapUserJobAsync` method in `SchedulerJobServiceCollectionExtensions.cs` for scheduling LDAP user sync tasks.
- Added `SyncFromLdapAsync` method in `UserService.cs` to trigger LDAP user synchronization via HTTP GET request.
=> feat: Update LDAP synchronization and related features

src/Web/Masa.Auth.Security.OAuth.Providers/Infrastructure/ThirdPartyIdpCaller/AlipayCaller.cs
Added logging statements in `AlipayCaller.cs` to capture details of Alipay token and user information requests. This includes logging the request method, address, and parameters to aid in debugging and monitoring API calls.
=> feat(AlipayCaller): add logging for token and userinfo requests

src/Web/Masa.Auth.Security.OAuth.Providers/Infrastructure/ThirdPartyIdpCaller/AlipayCaller.cs, src/Web/Masa.Auth.Web.Sso/Infrastructure/Validations/ThirdPartyIdpGrantValidator.cs
[fix](fix:weixin mini identity null)
=> fix:weixin mini identity null
